spring.application.name=resumeanalyzer

# Increase maximum file size limit (e.g., 10MB per file)
spring.servlet.multipart.max-file-size=10MB

# Increase maximum total request size limit (e.g., 10MB total)
spring.servlet.multipart.max-request-size=10MB

spring.ai.google.genai.api-key=YOUR_API_KEY
spring.ai.google.genai.chat.model=gemini-3.5-flash